/**
 * LabFlow Sentinel — Seed Dataset & Initial Data Models
 * Contains realistic Indian diagnostic laboratory clinical profiles,
 * test orders, multi-stage samples, analyzers, critical results, and audit events.
 */

const INITIAL_PATIENT_COUNTER = 48; // Next generated patient code will be 0049

const SEED_PATIENTS = [
  {
    patientCode: "0001",
    name: "Sunita Verma",
    age: 52,
    gender: "Female",
    phone: "+91 98234 11201",
    email: "sunita.v@example.com",
    address: "B-42, Sector 14, Noida, UP",
    referringDoctor: "Dr. R. K. Mehra (Endocrinologist)",
    registrationDate: "2026-09-08 08:30"
  },
  {
    patientCode: "0002",
    name: "Amitabh Sen",
    age: 64,
    gender: "Male",
    phone: "+91 98110 54321",
    email: "amitabh.sen@example.com",
    address: "74/3 Rashbehari Ave, Kolkata, WB",
    referringDoctor: "Dr. Ananya Roy (Cardiologist)",
    registrationDate: "2026-09-08 09:15"
  },
  {
    patientCode: "0003",
    name: "Pooja Deshmukh",
    age: 28,
    gender: "Female",
    phone: "+91 99702 33412",
    email: "pooja.d@example.com",
    address: "Flat 402, Shivneri Hsg, Pune, MH",
    referringDoctor: "Dr. Sandeep Kulkarni (General Phys)",
    registrationDate: "2026-09-08 10:00"
  },
  {
    patientCode: "0004",
    name: "Rajesh Iyer",
    age: 49,
    gender: "Male",
    phone: "+91 94441 98765",
    email: "rajesh.iyer@example.com",
    address: "12, 4th Cross, Malleshwaram, Bengaluru, KA",
    referringDoctor: "Dr. V. Ramanathan (Nephrologist)",
    registrationDate: "2026-09-08 11:20"
  },
  {
    patientCode: "0005",
    name: "Fatima Begum",
    age: 38,
    gender: "Female",
    phone: "+91 98480 65432",
    email: "fatima.b@example.com",
    address: "H.No 12-2-417, Mehdipatnam, Hyderabad, TS",
    referringDoctor: "Dr. Mohammed Tariq (Physician)",
    registrationDate: "2026-09-09 08:00"
  },
  {
    patientCode: "0006",
    name: "Vikramaditya Singh",
    age: 58,
    gender: "Male",
    phone: "+91 94140 22334",
    email: "vikram.singh@example.com",
    address: "Plot 8, Vaishali Nagar, Jaipur, RJ",
    referringDoctor: "Dr. K. S. Rathore (Diabetologist)",
    registrationDate: "2026-09-09 09:40"
  },
  {
    patientCode: "0007",
    name: "Meenakshi Sundaram",
    age: 61,
    gender: "Female",
    phone: "+91 98401 77889",
    email: "meenakshi.s@example.com",
    address: "22/1 Luz Church Rd, Mylapore, Chennai, TN",
    referringDoctor: "Dr. S. Balaji (Cardiologist)",
    registrationDate: "2026-09-09 10:15"
  },
  {
    patientCode: "0008",
    name: "Arjun Rampal",
    age: 34,
    gender: "Male",
    phone: "+91 98200 45678",
    email: "arjun.r@example.com",
    address: "601 Silver Beach, Juhu, Mumbai, MH",
    referringDoctor: "Dr. Neha Kapoor (Sports Physio)",
    registrationDate: "2026-09-09 11:05"
  },
  {
    patientCode: "0009",
    name: "Kavita Reddy",
    age: 45,
    gender: "Female",
    phone: "+91 99890 12345",
    email: "kavita.reddy@example.com",
    address: "Villa 14, Jubilee Hills, Hyderabad, TS",
    referringDoctor: "Dr. P. Sudhakar (Gynecologist)",
    registrationDate: "2026-09-09 14:30"
  },
  {
    patientCode: "0010",
    name: "Devendra Patel",
    age: 72,
    gender: "Male",
    phone: "+91 98250 99887",
    email: "devendra.p@example.com",
    address: "18 Ambawadi Heights, Ahmedabad, GJ",
    referringDoctor: "Dr. Chirag Shah (Gastroenterologist)",
    registrationDate: "2026-09-09 15:45"
  },
  {
    patientCode: "0011",
    name: "Smriti Chatterjee",
    age: 23,
    gender: "Female",
    phone: "+91 98300 11998",
    email: "smriti.c@example.com",
    address: "89 Lake Gardens, Kolkata, WB",
    referringDoctor: "Dr. T. Banerjee (General Phys)",
    registrationDate: "2026-09-09 16:30"
  },
  {
    patientCode: "0012",
    name: "Gurpreet Singh Gill",
    age: 50,
    gender: "Male",
    phone: "+91 98140 88776",
    email: "gurpreet.gill@example.com",
    address: "Model Town, Phase 2, Ludhiana, PB",
    referringDoctor: "Dr. Harpreet Kaur (Physician)",
    registrationDate: "2026-09-10 07:15"
  },
  {
    patientCode: "0013",
    name: "Ananya Nair",
    age: 31,
    gender: "Female",
    phone: "+91 94470 55443",
    email: "ananya.nair@example.com",
    address: "Panampilly Nagar, Kochi, KL",
    referringDoctor: "Dr. Jacob Varghese (Rheumatologist)",
    registrationDate: "2026-09-10 08:10"
  },
  {
    patientCode: "0014",
    name: "Manoj Joshi",
    age: 41,
    gender: "Male",
    phone: "+91 98901 23456",
    email: "manoj.joshi@example.com",
    address: "Deccan Gymkhana, Pune, MH",
    referringDoctor: "Dr. Shrikant Joshi (Pathologist)",
    registrationDate: "2026-09-10 08:45"
  },
  {
    patientCode: "0015",
    name: "Priya Sharma",
    age: 36,
    gender: "Female",
    phone: "+91 98101 22334",
    email: "priya.sharma@example.com",
    address: "Pocket C, Sarita Vihar, New Delhi, DL",
    referringDoctor: "Dr. Alok Nath (Physician)",
    registrationDate: "2026-09-10 09:20"
  },
  {
    patientCode: "0048",
    name: "Rahul Kumar",
    age: 42,
    gender: "Male",
    phone: "+91 98765 43210",
    email: "rahul.kumar@example.com",
    address: "Flat 304, Green Glen Layout, Bellandur, Bengaluru, KA",
    referringDoctor: "Dr. Arvind Swamy (Internal Medicine)",
    registrationDate: "2026-09-10 09:30"
  }
];

const SEED_ANALYZERS = [
  {
    id: "ANL-A",
    name: "Analyzer A",
    model: "Sysmex XN-1000",
    type: "Automated Hematology",
    capacity: 94,
    status: "Near Capacity",
    activeQueue: 14,
    maxThroughputPerHour: 40,
    supportedTests: ["CBC", "Hemoglobin", "Platelet Count", "ESR", "Peripheral Smear"],
    lastCalibration: "Today, 06:00 AM",
    warning: "Approaching operational ceiling. Compatible samples recommended for spillover."
  },
  {
    id: "ANL-B",
    name: "Analyzer B",
    model: "Roche Cobas c501",
    type: "Clinical Chemistry",
    capacity: 63,
    status: "Available",
    activeQueue: 7,
    maxThroughputPerHour: 60,
    supportedTests: ["Liver Function Test", "Kidney Function Test", "Lipid Profile", "Blood Glucose", "CRP", "HbA1c"],
    lastCalibration: "Today, 05:30 AM",
    warning: null
  },
  {
    id: "ANL-C",
    name: "Analyzer C",
    model: "Abbott Architect i2000SR",
    type: "Chemiluminescent Immunoassay",
    capacity: 38,
    status: "Available",
    activeQueue: 4,
    maxThroughputPerHour: 50,
    supportedTests: ["Thyroid Profile", "Vitamin D", "Troponin-I", "Serum Ferritin", "Beta-hCG"],
    lastCalibration: "Today, 06:15 AM",
    warning: null
  }
];

const SEED_SAMPLES = [
  {
    sampleId: "SMP-1048",
    patientCode: "0048",
    patientName: "Rahul Kumar",
    test: "CBC",
    sampleType: "Whole Blood (EDTA)",
    collectionTime: "2026-09-10 09:40",
    currentStage: "Analyzer Processing",
    stageIndex: 5,
    assignedAnalyzer: "Analyzer A",
    targetTat: 60, // minutes
    elapsedTime: 47, // minutes
    predictedCompletion: 58, // minutes
    riskScore: 87, // %
    riskLevel: "Critical",
    priority: "Urgent",
    status: "Delayed",
    reason: "Sample has remained in Analyzer A queue for 18 minutes while Analyzer A is operating at 94% capacity.",
    recommendation: "Move sample to Analyzer B or prioritize immediately on Stat Track.",
    rescueStatus: "Pending Approval",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 3.0
  },
  {
    sampleId: "SMP-1051",
    patientCode: "0002",
    patientName: "Amitabh Sen",
    test: "Troponin-I",
    sampleType: "Serum (SST)",
    collectionTime: "2026-09-10 10:00",
    currentStage: "Pre-Analytical Processing",
    stageIndex: 4,
    assignedAnalyzer: "Analyzer C",
    targetTat: 45,
    elapsedTime: 33,
    predictedCompletion: 46,
    riskScore: 82,
    riskLevel: "High",
    priority: "STAT",
    status: "Processing",
    reason: "STAT Troponin-I awaiting centrifuge completion. Risk of cardiac protocol TAT breach.",
    recommendation: "Expedite centrifuge decanting and manual accession directly to Analyzer C rack 1.",
    rescueStatus: "Recommended",
    temperature: "Cold Chain (4°C)",
    hemolysisLevel: "None",
    volumeMl: 4.5
  },
  {
    sampleId: "SMP-1062",
    patientCode: "0015",
    patientName: "Priya Sharma",
    test: "Lipid Profile",
    sampleType: "Serum (Plain)",
    collectionTime: "2026-09-10 09:30",
    currentStage: "Analyzer Processing",
    stageIndex: 5,
    assignedAnalyzer: "Analyzer B",
    targetTat: 90,
    elapsedTime: 71,
    predictedCompletion: 88,
    riskScore: 76,
    riskLevel: "High",
    priority: "Urgent",
    status: "Processing",
    reason: "Reagent pack B-2 undergoing automated probe wash cycle creating a 12-minute backlog.",
    recommendation: "Allow probe wash completion; buffer queue in temporary carousel.",
    rescueStatus: "Monitoring",
    temperature: "Room Temp (24°C)",
    hemolysisLevel: "Mild (1+)",
    volumeMl: 5.0
  },
  {
    sampleId: "SMP-1071",
    patientCode: "0004",
    patientName: "Rajesh Iyer",
    test: "Kidney Function Test",
    sampleType: "Serum (SST)",
    collectionTime: "2026-09-10 10:15",
    currentStage: "Sample Accessioned",
    stageIndex: 3,
    assignedAnalyzer: "Analyzer B",
    targetTat: 90,
    elapsedTime: 42,
    predictedCompletion: 74,
    riskScore: 54,
    riskLevel: "Moderate",
    priority: "Normal",
    status: "Received",
    reason: "Batch accession normal. Expected completion comfortably within acceptable limits.",
    recommendation: "Maintain standard batch processing schedule.",
    rescueStatus: "None",
    temperature: "Room Temp (23°C)",
    hemolysisLevel: "None",
    volumeMl: 4.0
  },
  {
    sampleId: "SMP-1080",
    patientCode: "0001",
    patientName: "Sunita Verma",
    test: "HbA1c",
    sampleType: "Whole Blood (EDTA)",
    collectionTime: "2026-09-10 09:00",
    currentStage: "Result Validation",
    stageIndex: 6,
    assignedAnalyzer: "Analyzer B",
    targetTat: 120,
    elapsedTime: 65,
    predictedCompletion: 75,
    riskScore: 19,
    riskLevel: "Low",
    priority: "Normal",
    status: "Processing",
    reason: "High HbA1c value (10.4%) requires technical delta-check review before Doctor sign-off.",
    recommendation: "Forward to Pathologist queue for review.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 2.5
  },
  {
    sampleId: "SMP-1085",
    patientCode: "0007",
    patientName: "Meenakshi Sundaram",
    test: "Thyroid Profile",
    sampleType: "Serum (SST)",
    collectionTime: "2026-09-10 09:15",
    currentStage: "Pathologist Review",
    stageIndex: 7,
    assignedAnalyzer: "Analyzer C",
    targetTat: 120,
    elapsedTime: 85,
    predictedCompletion: 95,
    riskScore: 22,
    riskLevel: "Low",
    priority: "Normal",
    status: "Processing",
    reason: "TSH markedly elevated (14.2 μIU/mL). Awaiting Pathologist signature.",
    recommendation: "Routine approval pending.",
    rescueStatus: "None",
    temperature: "Room Temp (21°C)",
    hemolysisLevel: "None",
    volumeMl: 4.0
  },
  {
    sampleId: "SMP-1088",
    patientCode: "0010",
    patientName: "Devendra Patel",
    test: "Liver Function Test",
    sampleType: "Serum (Plain)",
    collectionTime: "2026-09-10 08:30",
    currentStage: "Report Generated",
    stageIndex: 8,
    assignedAnalyzer: "Analyzer B",
    targetTat: 120,
    elapsedTime: 105,
    predictedCompletion: 105,
    riskScore: 12,
    riskLevel: "Low",
    priority: "Normal",
    status: "Completed",
    reason: "Report validated and ready for dispatch.",
    recommendation: "Send SMS/WhatsApp notification to patient.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 5.0
  },
  {
    sampleId: "SMP-1092",
    patientCode: "0003",
    patientName: "Pooja Deshmukh",
    test: "CBC",
    sampleType: "Whole Blood (EDTA)",
    collectionTime: "2026-09-10 10:20",
    currentStage: "Sample Collected",
    stageIndex: 2,
    assignedAnalyzer: "Analyzer A",
    targetTat: 60,
    elapsedTime: 12,
    predictedCompletion: 48,
    riskScore: 28,
    riskLevel: "Low",
    priority: "Normal",
    status: "Collected",
    reason: "Fresh collection, phlebotomy complete. En route to accession desk.",
    recommendation: "Check-in upon receipt at central sorting.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 3.0
  },
  {
    sampleId: "SMP-1095",
    patientCode: "0005",
    patientName: "Fatima Begum",
    test: "Blood Glucose (F)",
    sampleType: "Plasma (Fluoride)",
    collectionTime: "2026-09-10 08:15",
    currentStage: "Patient Notified",
    stageIndex: 9,
    assignedAnalyzer: "Analyzer B",
    targetTat: 60,
    elapsedTime: 52,
    predictedCompletion: 52,
    riskScore: 5,
    riskLevel: "Low",
    priority: "Normal",
    status: "Completed",
    reason: "Workflow completed and report delivered digitally.",
    recommendation: "Archived.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 2.0
  },
  {
    sampleId: "SMP-1099",
    patientCode: "0006",
    patientName: "Vikramaditya Singh",
    test: "Urine Routine",
    sampleType: "Urine (Sterile Cup)",
    collectionTime: "2026-09-10 09:45",
    currentStage: "Pre-Analytical Processing",
    stageIndex: 4,
    assignedAnalyzer: "Manual Bench / Clinitek",
    targetTat: 60,
    elapsedTime: 38,
    predictedCompletion: 54,
    riskScore: 35,
    riskLevel: "Moderate",
    priority: "Normal",
    status: "Processing",
    reason: "Centrifugation for sediment microscopy queued.",
    recommendation: "Proceed with slide examination.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "N/A",
    volumeMl: 25.0
  },
  {
    sampleId: "SMP-1102",
    patientCode: "0008",
    patientName: "Arjun Rampal",
    test: "Vitamin D (25-OH)",
    sampleType: "Serum (SST)",
    collectionTime: "2026-09-10 08:40",
    currentStage: "Analyzer Processing",
    stageIndex: 5,
    assignedAnalyzer: "Analyzer C",
    targetTat: 180,
    elapsedTime: 95,
    predictedCompletion: 140,
    riskScore: 24,
    riskLevel: "Low",
    priority: "Normal",
    status: "Processing",
    reason: "Chemiluminescence incubation in progress.",
    recommendation: "Standard run.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 4.0
  },
  {
    sampleId: "SMP-1105",
    patientCode: "0009",
    patientName: "Kavita Reddy",
    test: "CRP (Quantitative)",
    sampleType: "Serum (Plain)",
    collectionTime: "2026-09-10 10:05",
    currentStage: "Pre-Analytical Processing",
    stageIndex: 4,
    assignedAnalyzer: "Analyzer B",
    targetTat: 60,
    elapsedTime: 25,
    predictedCompletion: 45,
    riskScore: 31,
    riskLevel: "Low",
    priority: "Normal",
    status: "Processing",
    reason: "Turbidimetric assay sample pipetted.",
    recommendation: "Awaiting run cycle.",
    rescueStatus: "None",
    temperature: "Room Temp (23°C)",
    hemolysisLevel: "None",
    volumeMl: 3.5
  },
  {
    sampleId: "SMP-1110",
    patientCode: "0011",
    patientName: "Smriti Chatterjee",
    test: "CBC",
    sampleType: "Whole Blood (EDTA)",
    collectionTime: "2026-09-10 10:10",
    currentStage: "Analyzer Processing",
    stageIndex: 5,
    assignedAnalyzer: "Analyzer A",
    targetTat: 60,
    elapsedTime: 39,
    predictedCompletion: 56,
    riskScore: 68,
    riskLevel: "Moderate",
    priority: "Urgent",
    status: "Processing",
    reason: "Analyzer A queue delays impacting turnaround.",
    recommendation: "Monitor rack progress.",
    rescueStatus: "Monitoring",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 3.0
  },
  {
    sampleId: "SMP-1114",
    patientCode: "0012",
    patientName: "Gurpreet Singh Gill",
    test: "Lipid Profile",
    sampleType: "Serum (Plain)",
    collectionTime: "2026-09-10 07:30",
    currentStage: "Patient Notified",
    stageIndex: 9,
    assignedAnalyzer: "Analyzer B",
    targetTat: 120,
    elapsedTime: 110,
    predictedCompletion: 110,
    riskScore: 8,
    riskLevel: "Low",
    priority: "Normal",
    status: "Completed",
    reason: "Delivered to referring doctor and patient app.",
    recommendation: "Archived.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 4.5
  },
  {
    sampleId: "SMP-1118",
    patientCode: "0013",
    patientName: "Ananya Nair",
    test: "CRP (Quantitative)",
    sampleType: "Serum (SST)",
    collectionTime: "2026-09-10 08:50",
    currentStage: "Result Validation",
    stageIndex: 6,
    assignedAnalyzer: "Analyzer B",
    targetTat: 60,
    elapsedTime: 55,
    predictedCompletion: 59,
    riskScore: 71,
    riskLevel: "High",
    priority: "Urgent",
    status: "Delayed",
    reason: "Extremely elevated CRP (88 mg/L). Requires clinical correlation validation.",
    recommendation: "Pathologist immediate review required.",
    rescueStatus: "Recommended",
    temperature: "Room Temp (23°C)",
    hemolysisLevel: "None",
    volumeMl: 3.0
  },
  {
    sampleId: "SMP-1122",
    patientCode: "0014",
    patientName: "Manoj Joshi",
    test: "Liver Function Test",
    sampleType: "Serum (Plain)",
    collectionTime: "2026-09-10 09:10",
    currentStage: "Analyzer Processing",
    stageIndex: 5,
    assignedAnalyzer: "Analyzer B",
    targetTat: 90,
    elapsedTime: 62,
    predictedCompletion: 80,
    riskScore: 48,
    riskLevel: "Moderate",
    priority: "Normal",
    status: "Processing",
    reason: "Assay photometric reading in progress.",
    recommendation: "Maintain queue.",
    rescueStatus: "None",
    temperature: "Room Temp (23°C)",
    hemolysisLevel: "None",
    volumeMl: 5.0
  },
  {
    sampleId: "SMP-1125",
    patientCode: "0048",
    patientName: "Rahul Kumar",
    test: "Lipid Profile",
    sampleType: "Serum (SST)",
    collectionTime: "2026-09-10 09:40",
    currentStage: "Pre-Analytical Processing",
    stageIndex: 4,
    assignedAnalyzer: "Analyzer B",
    targetTat: 90,
    elapsedTime: 40,
    predictedCompletion: 70,
    riskScore: 42,
    riskLevel: "Moderate",
    priority: "Normal",
    status: "Processing",
    reason: "Centrifuged and transferred to biochemistry rack.",
    recommendation: "Standard processing.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 4.0
  },
  {
    sampleId: "SMP-1129",
    patientCode: "0002",
    patientName: "Amitabh Sen",
    test: "Kidney Function Test",
    sampleType: "Serum (Plain)",
    collectionTime: "2026-09-10 10:00",
    currentStage: "Sample Accessioned",
    stageIndex: 3,
    assignedAnalyzer: "Analyzer B",
    targetTat: 90,
    elapsedTime: 22,
    predictedCompletion: 68,
    riskScore: 30,
    riskLevel: "Low",
    priority: "Urgent",
    status: "Received",
    reason: "Awaiting centrifuge slot.",
    recommendation: "Group with next centrifuge batch.",
    rescueStatus: "None",
    temperature: "Room Temp (22°C)",
    hemolysisLevel: "None",
    volumeMl: 4.5
  },
  {
    sampleId: "SMP-1133",
    patientCode: "0015",
    patientName: "Priya Sharma",
    test: "Thyroid Profile",
    sampleType: "Serum (SST)",
    collectionTime: "2026-09-10 09:30",
    currentStage: "Pre-Analytical Processing",
    stageIndex: 4,
    assignedAnalyzer: "Analyzer C",
    targetTat: 120,
    elapsedTime: 45,
    predictedCompletion: 85,
    riskScore: 26,
    riskLevel: "Low",
    priority: "Normal",
    status: "Processing",
    reason: "Pipetting queue for Immunoassay carousel.",
    recommendation: "Normal flow.",
    rescueStatus: "None",
    temperature: "Room Temp (21°C)",
    hemolysisLevel: "None",
    volumeMl: 3.5
  },
  {
    sampleId: "SMP-1137",
    patientCode: "0007",
    patientName: "Meenakshi Sundaram",
    test: "Blood Glucose (PP)",
    sampleType: "Plasma (Fluoride)",
    collectionTime: "2026-09-10 10:25",
    currentStage: "Test Ordered",
    stageIndex: 1,
    assignedAnalyzer: "Analyzer B",
    targetTat: 60,
    elapsedTime: 5,
    predictedCompletion: 45,
    riskScore: 10,
    riskLevel: "Low",
    priority: "Normal",
    status: "Waiting",
    reason: "Patient awaiting 2-hour post-prandial venipuncture.",
    recommendation: "Schedule venipuncture draw at 11:15 AM.",
    rescueStatus: "None",
    temperature: "N/A",
    hemolysisLevel: "N/A",
    volumeMl: 0
  }
];

const SEED_TEST_ORDERS = [
  { orderId: "ORD-901", patientCode: "0048", testName: "CBC", doctor: "Dr. Arvind Swamy", priority: "Urgent", orderTime: "2026-09-10 09:30", status: "In Progress" },
  { orderId: "ORD-902", patientCode: "0048", testName: "Lipid Profile", doctor: "Dr. Arvind Swamy", priority: "Normal", orderTime: "2026-09-10 09:30", status: "In Progress" },
  { orderId: "ORD-903", patientCode: "0002", testName: "Troponin-I", doctor: "Dr. Ananya Roy", priority: "STAT", orderTime: "2026-09-10 09:55", status: "In Progress" },
  { orderId: "ORD-904", patientCode: "0002", testName: "Kidney Function Test", doctor: "Dr. Ananya Roy", priority: "Urgent", orderTime: "2026-09-10 09:55", status: "In Progress" },
  { orderId: "ORD-905", patientCode: "0015", testName: "Lipid Profile", doctor: "Dr. Alok Nath", priority: "Urgent", orderTime: "2026-09-10 09:20", status: "In Progress" },
  { orderId: "ORD-906", patientCode: "0015", testName: "Thyroid Profile", doctor: "Dr. Alok Nath", priority: "Normal", orderTime: "2026-09-10 09:20", status: "In Progress" },
  { orderId: "ORD-907", patientCode: "0004", testName: "Kidney Function Test", doctor: "Dr. V. Ramanathan", priority: "Normal", orderTime: "2026-09-10 10:05", status: "In Progress" },
  { orderId: "ORD-908", patientCode: "0001", testName: "HbA1c", doctor: "Dr. R. K. Mehra", priority: "Normal", orderTime: "2026-09-10 08:45", status: "Under Review" },
  { orderId: "ORD-909", patientCode: "0007", testName: "Thyroid Profile", doctor: "Dr. S. Balaji", priority: "Normal", orderTime: "2026-09-10 09:05", status: "Under Review" },
  { orderId: "ORD-910", patientCode: "0007", testName: "Blood Glucose (PP)", doctor: "Dr. S. Balaji", priority: "Normal", orderTime: "2026-09-10 10:20", status: "Scheduled" },
  { orderId: "ORD-911", patientCode: "0010", testName: "Liver Function Test", doctor: "Dr. Chirag Shah", priority: "Normal", orderTime: "2026-09-10 08:20", status: "Completed" },
  { orderId: "ORD-912", patientCode: "0003", testName: "CBC", doctor: "Dr. Sandeep Kulkarni", priority: "Normal", orderTime: "2026-09-10 10:10", status: "Sample Drawn" },
  { orderId: "ORD-913", patientCode: "0005", testName: "Blood Glucose (F)", doctor: "Dr. Mohammed Tariq", priority: "Normal", orderTime: "2026-09-10 08:05", status: "Completed" },
  { orderId: "ORD-914", patientCode: "0006", testName: "Urine Routine", doctor: "Dr. K. S. Rathore", priority: "Normal", orderTime: "2026-09-10 09:35", status: "In Progress" },
  { orderId: "ORD-915", patientCode: "0008", testName: "Vitamin D (25-OH)", doctor: "Dr. Neha Kapoor", priority: "Normal", orderTime: "2026-09-10 08:35", status: "In Progress" },
  { orderId: "ORD-916", patientCode: "0009", testName: "CRP (Quantitative)", doctor: "Dr. P. Sudhakar", priority: "Normal", orderTime: "2026-09-10 09:55", status: "In Progress" },
  { orderId: "ORD-917", patientCode: "0011", testName: "CBC", doctor: "Dr. T. Banerjee", priority: "Urgent", orderTime: "2026-09-10 10:00", status: "In Progress" },
  { orderId: "ORD-918", patientCode: "0012", testName: "Lipid Profile", doctor: "Dr. Harpreet Kaur", priority: "Normal", orderTime: "2026-09-10 07:20", status: "Completed" },
  { orderId: "ORD-919", patientCode: "0013", testName: "CRP (Quantitative)", doctor: "Dr. Jacob Varghese", priority: "Urgent", orderTime: "2026-09-10 08:40", status: "Under Review" },
  { orderId: "ORD-920", patientCode: "0014", testName: "Liver Function Test", doctor: "Dr. Shrikant Joshi", priority: "Normal", orderTime: "2026-09-10 09:00", status: "In Progress" },
  { orderId: "ORD-921", patientCode: "0001", testName: "Lipid Profile", doctor: "Dr. R. K. Mehra", priority: "Normal", orderTime: "2026-09-08 08:45", status: "Completed" },
  { orderId: "ORD-922", patientCode: "0002", testName: "CBC", doctor: "Dr. Ananya Roy", priority: "Urgent", orderTime: "2026-09-08 09:20", status: "Completed" },
  { orderId: "ORD-923", patientCode: "0004", testName: "Blood Glucose (F)", doctor: "Dr. V. Ramanathan", priority: "Normal", orderTime: "2026-09-08 11:30", status: "Completed" },
  { orderId: "ORD-924", patientCode: "0006", testName: "HbA1c", doctor: "Dr. K. S. Rathore", priority: "Normal", orderTime: "2026-09-09 09:50", status: "Completed" },
  { orderId: "ORD-925", patientCode: "0008", testName: "CBC", doctor: "Dr. Neha Kapoor", priority: "Normal", orderTime: "2026-09-09 11:15", status: "Completed" }
];

const SEED_CRITICAL_RESULTS = [
  {
    resultId: "RES-501",
    patientCode: "0048",
    patientName: "Rahul Kumar",
    sampleId: "SMP-1048",
    test: "CBC — Platelet Count",
    value: "18,000",
    unit: "/μL",
    referenceRange: "150,000 - 450,000",
    status: "Critical Alert",
    flag: "CRITICAL LOW",
    reviewer: "Awaiting Pathologist Sign-off",
    timestamp: "2026-09-10 10:18",
    clinicalNotes: "Severe thrombocytopenia detected. Bleeding risk high. Peripheral blood smear examination advised to rule out EDTA clumping.",
    historicalValue: "210,000 /μL (3 months ago)",
    deltaDeviation: "-91.4% drop from historical baseline"
  },
  {
    resultId: "RES-502",
    patientCode: "0002",
    patientName: "Amitabh Sen",
    sampleId: "SMP-1051",
    test: "Troponin-I (High Sensitivity)",
    value: "0.48",
    unit: "ng/mL",
    referenceRange: "< 0.04",
    status: "Critical Alert",
    flag: "CRITICAL HIGH",
    reviewer: "Dr. Priya S. (Pathologist)",
    timestamp: "2026-09-10 10:22",
    clinicalNotes: "Marked myocardial injury marker elevation. Immediate telephonic callout to cardiologist Dr. Ananya Roy.",
    historicalValue: "0.02 ng/mL (6 months ago)",
    deltaDeviation: "+2300% acute rise"
  },
  {
    resultId: "RES-503",
    patientCode: "0004",
    patientName: "Rajesh Iyer",
    sampleId: "SMP-1071",
    test: "Serum Potassium (K+)",
    value: "6.8",
    unit: "mEq/L",
    referenceRange: "3.5 - 5.0",
    status: "Critical Alert",
    flag: "CRITICAL HIGH",
    reviewer: "Dr. Priya S. (Pathologist)",
    timestamp: "2026-09-10 10:24",
    clinicalNotes: "Severe hyperkalemia. Risk of cardiac arrhythmia. Specimen re-checked for non-hemolyzed status.",
    historicalValue: "4.9 mEq/L (1 month ago)",
    deltaDeviation: "+38.7% rise"
  },
  {
    resultId: "RES-504",
    patientCode: "0001",
    patientName: "Sunita Verma",
    sampleId: "SMP-1080",
    test: "Blood Glucose (Random)",
    value: "482",
    unit: "mg/dL",
    referenceRange: "70 - 140",
    status: "Critical Alert",
    flag: "CRITICAL HIGH",
    reviewer: "Awaiting Review",
    timestamp: "2026-09-10 10:12",
    clinicalNotes: "Severe hyperglycemia with glycosuria. Check urine ketone bodies to rule out DKA.",
    historicalValue: "188 mg/dL (2 weeks ago)",
    deltaDeviation: "+156% surge"
  },
  {
    resultId: "RES-505",
    patientCode: "0013",
    patientName: "Ananya Nair",
    sampleId: "SMP-1118",
    test: "CRP (High Sensitivity)",
    value: "88.4",
    unit: "mg/L",
    referenceRange: "< 5.0",
    status: "Flagged High",
    flag: "ALERT HIGH",
    reviewer: "Awaiting Review",
    timestamp: "2026-09-10 10:14",
    clinicalNotes: "Severe systemic acute inflammatory surge. Clinical correlation advised.",
    historicalValue: "6.2 mg/L (4 months ago)",
    deltaDeviation: "+1325% surge"
  }
];

const SEED_AI_INSIGHTS = [
  {
    id: "INS-01",
    type: "TAT_BREACH_RISK",
    severity: "Critical",
    title: "1 Sample at Imminent Risk of TAT Breach (<15 min)",
    sampleId: "SMP-1048",
    patientCode: "0048",
    description: "Sample SMP-1048 (Rahul Kumar, CBC) has 13 min remaining with 11 min estimated processing time. Analyzer A queue bottleneck.",
    reason: "Analyzer A running at 94% utilization with 14 active samples ahead in rack.",
    recommendation: "Execute Rescue Action: Shift sample to Analyzer B or expedite on STAT priority track.",
    actionText: "Rescue Sample",
    actionTarget: "rescue",
    timestamp: "2 min ago"
  },
  {
    id: "INS-02",
    type: "ANALYZER_BOTTLENECK",
    severity: "High",
    title: "Analyzer A Approaching Saturation Capacity",
    analyzerId: "ANL-A",
    description: "Sysmex XN-1000 is operating at 94% utilization. Predictive model estimates full capacity saturation in 22 minutes.",
    reason: "Morning surge of routine CBC orders coupled with 3 STAT requests.",
    recommendation: "Redirect upcoming compatible hematology workload to secondary backup lane.",
    actionText: "Rebalance Load",
    actionTarget: "operations",
    timestamp: "5 min ago"
  },
  {
    id: "INS-03",
    type: "PRIORITY_ESCALATION",
    severity: "High",
    title: "STAT Troponin-I Awaiting Pre-Analytical Centrifuge",
    sampleId: "SMP-1051",
    patientCode: "0002",
    description: "Cardiac marker sample has been waiting in pre-analytical accession for 14 minutes.",
    reason: "Centrifuge unit 2 cycle currently running; 4 minutes remaining on timer.",
    recommendation: "Prioritize decapping and load into Analyzer C immediate emergency slot.",
    actionText: "Expedite Centrifuge",
    actionTarget: "samples",
    timestamp: "7 min ago"
  },
  {
    id: "INS-04",
    type: "CRITICAL_RESULT_ACTION",
    severity: "Critical",
    title: "Critical Platelet Result (18,000 /μL) Requires Validation",
    sampleId: "SMP-1048",
    patientCode: "0048",
    description: "Severe thrombocytopenia flag generated. Laboratory SOP requires smear correlation before report release.",
    reason: "Delta check failed: 91.4% drop compared to historical baseline 3 months prior.",
    recommendation: "Pathologist to review peripheral smear and approve critical value notification.",
    actionText: "Review Result",
    actionTarget: "results",
    timestamp: "8 min ago"
  },
  {
    id: "INS-05",
    type: "WORKFLOW_ANOMALY",
    severity: "Medium",
    title: "Unusual Pre-Analytical Holding Time Detected",
    sampleId: "SMP-1062",
    patientCode: "0015",
    description: "Serum sample SMP-1062 held 18 minutes post-centrifugation before rack placement.",
    reason: "Probe wash cycle delay on Analyzer B.",
    recommendation: "Keep sample refrigerated if analyzer downtime exceeds 20 minutes.",
    actionText: "View Sample",
    actionTarget: "samples",
    timestamp: "12 min ago"
  }
];

const SEED_NOTIFICATIONS = [
  { id: "NTF-1", type: "critical", title: "Critical Alert: Low Platelets", message: "Patient 0048 (Rahul Kumar) Platelets: 18,000 /μL. Immediate review required.", time: "10:18 AM", read: false, linkTarget: "results" },
  { id: "NTF-2", type: "tat", title: "TAT Breach Warning", message: "Sample SMP-1048 projected to breach turnaround time in 13 minutes.", time: "10:15 AM", read: false, linkTarget: "rescue" },
  { id: "NTF-3", type: "analyzer", title: "Analyzer A Load Warning", message: "Sysmex XN-1000 capacity reached 94%. Bottleneck predicted.", time: "10:10 AM", read: false, linkTarget: "operations" },
  { id: "NTF-4", type: "ai", title: "AI Rescue Plan Ready", message: "AI suggested 1 sample reroute action to prevent TAT failure.", time: "10:08 AM", read: true, linkTarget: "rescue" },
  { id: "NTF-5", type: "system", title: "Daily QC Calibration Verified", message: "All 3 automated analyzers successfully passed morning quality controls.", time: "06:30 AM", read: true, linkTarget: "operations" }
];

const SEED_AUDIT_LOGS = [
  { id: "AUD-101", timestamp: "10:24 AM", user: "Dr. Priya Sharma", role: "Pathologist", action: "Flagged Critical Result", object: "SMP-1071 (Potassium 6.8 mEq/L)", previousValue: "Pending Review", newValue: "Critical Alert Verified" },
  { id: "AUD-102", timestamp: "10:22 AM", user: "Dr. Priya Sharma", role: "Pathologist", action: "Clinical Callout Logged", object: "SMP-1051 (Troponin-I 0.48 ng/mL)", previousValue: "Unnotified", newValue: "Cardiologist Contacted" },
  { id: "AUD-103", timestamp: "10:18 AM", user: "System (AI Engine)", role: "AI Decision Support", action: "Generated Rescue Recommendation", object: "SMP-1048", previousValue: "Standard Queue", newValue: "Rescue Flag: Reassign to Analyzer B" },
  { id: "AUD-104", timestamp: "10:05 AM", user: "Vikram Rathore", role: "Lab Technician", action: "Sample Accessioned", object: "SMP-1071", previousValue: "In Transit", newValue: "Accession Verified" },
  { id: "AUD-105", timestamp: "09:40 AM", user: "Sunil Verma", role: "Receptionist", action: "Patient Registered", object: "Patient Code 0048 (Rahul Kumar)", previousValue: "N/A", newValue: "Registered" },
  { id: "AUD-106", timestamp: "09:42 AM", user: "Sunil Verma", role: "Receptionist", action: "Test Order Created", object: "ORD-901 (CBC for 0048)", previousValue: "N/A", newValue: "Urgent Order Created" },
  { id: "AUD-107", timestamp: "09:44 AM", user: "Nurse Rekha", role: "Phlebotomist", action: "Sample Collected", object: "SMP-1048 (Whole Blood EDTA)", previousValue: "Pending Draw", newValue: "Collected" },
  { id: "AUD-108", timestamp: "09:30 AM", user: "Dr. Alok Nath", role: "Doctor", action: "Reviewed Completed Report", object: "Patient Code 0010", previousValue: "Report Generated", newValue: "Report Viewed" },
  { id: "AUD-109", timestamp: "09:15 AM", user: "Dr. Priya Sharma", role: "Pathologist", action: "Digitally Signed Report", object: "RPT-802 (Patient 0012)", previousValue: "Pending Approval", newValue: "Approved & Stamped" },
  { id: "AUD-110", timestamp: "09:00 AM", user: "System", role: "Automated SMS Gateway", action: "Patient Dispatched Notification", object: "Patient Code 0012", previousValue: "Pending Notification", newValue: "Delivered via SMS" },
  { id: "AUD-111", timestamp: "08:30 AM", user: "Vikram Rathore", role: "Lab Technician", action: "Analyzer QC Calibrated", object: "Analyzer A, B, C", previousValue: "Pending QC", newValue: "QC Normal" },
  { id: "AUD-112", timestamp: "08:15 AM", user: "Dr. Priya Sharma", role: "Pathologist", action: "User Authenticated", object: "Session Login", previousValue: "Logged Out", newValue: "Pathologist Session Active" },
  { id: "AUD-113", timestamp: "08:00 AM", user: "Admin (Lab Ops)", role: "Laboratory Administrator", action: "TAT Threshold Modified", object: "STAT Turnaround Time", previousValue: "60 mins", newValue: "45 mins" },
  { id: "AUD-114", timestamp: "07:45 AM", user: "Sunil Verma", role: "Receptionist", action: "Patient Registered", object: "Patient Code 0015 (Priya Sharma)", previousValue: "N/A", newValue: "Registered" },
  { id: "AUD-115", timestamp: "07:30 AM", user: "Vikram Rathore", role: "Lab Technician", action: "Reagent Lot Loaded", object: "Roche Cobas c501 (Biochem)", previousValue: "Lot #9401", newValue: "Lot #9402 Verified" }
];

const TEN_STAGE_JOURNEY = [
  { index: 1, id: "reg", title: "Patient Registration", responsibleRole: "Receptionist", typicalDuration: "5-10 min" },
  { index: 2, id: "order", title: "Test Ordered", responsibleRole: "Receptionist / Doctor", typicalDuration: "5 min" },
  { index: 3, id: "collect", title: "Sample Collected", responsibleRole: "Phlebotomist", typicalDuration: "10-15 min" },
  { index: 4, id: "accession", title: "Sample Accessioned", responsibleRole: "Lab Technician", typicalDuration: "5-10 min" },
  { index: 5, id: "pre_analyt", title: "Pre-Analytical Processing", responsibleRole: "Lab Technician", typicalDuration: "15-20 min" },
  { index: 6, id: "analyzer", title: "Analyzer Processing", responsibleRole: "Automated Analyzer", typicalDuration: "20-40 min" },
  { index: 7, id: "validation", title: "Result Validation", responsibleRole: "Senior Technician", typicalDuration: "10-15 min" },
  { index: 8, id: "review", title: "Doctor / Pathologist Review", responsibleRole: "Pathologist", typicalDuration: "15-30 min" },
  { index: 9, id: "report", title: "Report Generated", responsibleRole: "LIMS / Sentinel Engine", typicalDuration: "Instant" },
  { index: 10, id: "notify", title: "Patient Notification", responsibleRole: "Automated Dispatch", typicalDuration: "Instant" }
];
